use_frameworks!

platform :ios, '11.0'

target 'JFDynamicLottie_Example' do
  pod 'JFDynamicLottie', :path => '../'
  pod 'JFPopup'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
             end
        end
      end
  end

  target 'JFDynamicLottie_Tests' do
    inherit! :search_paths

    
  end
end
